"""add UsersConfig table

Revision ID: 457ada8574e7
Revises: 174610b22d3e
Create Date: 2026-09-17 10:40:12.827408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457ada8574e7'
down_revision = '174610b22d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.String(length=250), nullable=False),
    sa.Column('token_uri', sa.String(length=250), nullable=False),
    sa.Column('client_id', sa.String(length=250), nullable=False),
    sa.Column('client_secret', sa.String(length=250), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersconfig')
    # ### end Alembic commands ###
